export enum EventType {
	MENTOR_SESSION = 'MENTOR_SESSION',
	PANEL_DISCUSSION = 'PANEL_DISCUSSION',
	COMMUNITY_ADDA = 'COMMUNITY_ADDA',
	MEETUP = 'MEETUP'
}

export enum EventFormat {
	ONLINE = 'ONLINE',
	PHYSICAL = 'PHYSICAL',
	HYBRID = 'HYBRID'
}
