export enum ActivityType {
	JOINED_PLATFORM = 'JOINED_PLATFORM',
	BECAME_MENTOR = 'BECAME_MENTOR',
	PUBLISHED_ARTICLE = 'PUBLISHED_ARTICLE',
	PUBLISHED_CASE_STUDY = 'PUBLISHED_CASE_STUDY',
	LAUNCHED_PRODUCT = 'LAUNCHED_PRODUCT',
	ATTENDED_EVENT = 'ATTENDED_EVENT',
	SPOKE_AT_EVENT = 'SPOKE_AT_EVENT',
	JOINED_CONTEST = 'JOINED_CONTEST',
	WON_CONTEST = 'WON_CONTEST',
	JUDGED_CONTEST = 'JUDGED_CONTEST',
	FOLLOWER_MILESTONE = 'FOLLOWER_MILESTONE'
}

export enum TimelineOrder {
	LATEST_FIRST = 'LATEST_FIRST',
	OLDEST_FIRST = 'OLDEST_FIRST'
}

export enum ProfileTab {
	TIMELINE = 'timeline',
	ABOUT = 'about',
	CONTENT = 'content',
	CONTESTS = 'contests'
}
